### ISSUE TITLE
Confused about the results compared with spellgcn

### ISSUE THREAD

**Issue by YsylviaUC** [mnhng/HeadFilt#2]
After reading your paper many times, I found that the result of Spellgcn you adopted is not the result of using evaluation tools provided by the CSC Bake-offs. 
 The performance of BERT and SpellGCN evaluated by official tools on SIGHAN 2014 and SIGHAN 2015 is:
![image](https://user-images.githubusercontent.com/35765593/136719562-da2fa7e0-9204-4fa2-9980-40bdc899c7fb.png)
Your result is different from this one. So I'm confused. Please help me solve it.

**Comment by mnhng** [comment]
See [appendix](https://ieeexplore.ieee.org/abstract/document/9439969)

**Comment by smell-iron** [comment]
What is the version of Anaconda？I can‘t have a result in Train base classifier on CSC 2015 (Simplified text)，and I suspect the problem has something to do with version of conda. Thank you.
