### ISSUE TITLE
use treelstm code

### ISSUE THREAD

**Issue by TheJun1999** [mnhng/HeadFilt#5]
If I want to use the treeLSTM code in the project, what should I do? Or you can tell me the meaning and usage of the involved txt file treeLSTM. I would appreciate it very much if you could reply to me.

**Comment by mnhng** [comment]
You can look at this example from https://github.com/mnhng/hier-char-emb
The *HierarchicalEmbedding* class is based on treeLSTM.

```
import torch
from nnblk import HierarchicalEmbedding

char2index = {'白': 0, '山': 1, '名': 2, '風': 3}
emb = HierarchicalEmbedding(num_embeddings=len(char2index), embedding_dim=4, char2index=char2index)
input_ = torch.LongTensor(list(char2index.values()))
print(emb(input_))
```
